[workspace]
members = ["day-1", "day-2", "day-3", "day-4", "day-5", "day-6"]
resolver = "2"

[workspace.package]
version = "0.1.0"
authors = ["Luka Paulic luka.paulic0@gmail.com"]
description = "Advent of Code 2023"